[package]
name = "rax"
version = "0.1.0"
authors = ["Clay Molocznik <clay@mojo.run>"]
build = "build.rs"

[lib]
bench = false
crate-type = ["dylib", "rlib"]

[dependencies]
libc = "0.2"
num = "*"
stopwatch = "0.0.7"

[dev-dependencies]
bencher = "0.1.5"

[build-dependencies]
gcc = "0.3"